### ISSUE TITLE
sveltia unexpected error loading local repo

### ISSUE THREAD

**Issue by richtong** [Hugolify/hugolify-sveltia-cms#2]
Thanks so much for your hard work. I don't know how much this is maintained, but I tried to use your hugo module for sveltia

```
baseURL: /
languageCode: en-us
title: My New Hugo Site
module:
  imports:
    - path: github.com/richtong/gohugo-theme-ananke
    - path: github.com/hugolify/hugolify-sveltia-cms
```

I do indeed get to the sveltia site with `localhost:1313/admin`

I'm using Chrome (and made the adjustments so Brave works), but when I browse to a repo, I get

![image](https://github.com/user-attachments/assets/e63abe1b-44d5-4536-a612-b06af2178061)

and then i get this error. Looking at the code here, I don't see an obvious problem it is basically replacing the decap js include with sveltia.

![image](https://github.com/user-attachments/assets/9d322c36-793d-4023-a89a-ea186d822402)
